name: corotating_merge
mesh:
  type: None 
  maxV: 1.0e-4
  marker_boundary: 2
  bounds: [-1.5, 1.5, -1.5, 1.5]
kwargs:
  gamma: 1.4
  mu: 1.716e-4
  R: 287
  k: 0.30780
  flag_NS: True
  alpha: 1.
initial_condition:
  type: corotating_merge
  params:
    Gamma: 1.0
    r0: 0.18
    D0: 1.0
    center: [0., 0.]
time:
  cfl: 0.4
  t_end: 40.0
  scheme: rk2